// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkLRbdq118qPZpTKDxKWYSQmxQZAQ1sRM',
    appId: '1:825728375164:web:cb2b942543f7ec687aecf9',
    messagingSenderId: '825728375164',
    projectId: 'grievancapp',
    authDomain: 'grievancapp.firebaseapp.com',
    storageBucket: 'grievancapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwWhg4udHjByesMaVlZ8uPcG_Wqxjb4ec',
    appId: '1:825728375164:android:88cff9542c7589627aecf9',
    messagingSenderId: '825728375164',
    projectId: 'grievancapp',
    storageBucket: 'grievancapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChlNfhMf7O-oUUBADRdlZcnQAN80whg80',
    appId: '1:825728375164:ios:e50e04b7189b22b47aecf9',
    messagingSenderId: '825728375164',
    projectId: 'grievancapp',
    storageBucket: 'grievancapp.firebasestorage.app',
    iosBundleId: 'com.example.grievance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChlNfhMf7O-oUUBADRdlZcnQAN80whg80',
    appId: '1:825728375164:ios:e50e04b7189b22b47aecf9',
    messagingSenderId: '825728375164',
    projectId: 'grievancapp',
    storageBucket: 'grievancapp.firebasestorage.app',
    iosBundleId: 'com.example.grievance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkLRbdq118qPZpTKDxKWYSQmxQZAQ1sRM',
    appId: '1:825728375164:web:75096ed4b72ac1617aecf9',
    messagingSenderId: '825728375164',
    projectId: 'grievancapp',
    authDomain: 'grievancapp.firebaseapp.com',
    storageBucket: 'grievancapp.firebasestorage.app',
  );
}
